apiVersion: apps/v1
kind: Deployment
metadata:
  name: starbucks-poc
  labels:
    app: starbucks-poc
spec:
  replicas: 3
  selector:
    matchLabels:
      app: starbucks-poc
  template:
    metadata:
      labels:
        app: starbucks-poc
    spec:
      containers:
        - name: starbucks-poc
          image: 975049886839.dkr.ecr.us-east-1.amazonaws.com/starbucks:b71dac73295c3428a124bb257286ce1d14f673c6
          # Image will be automatically updated by CI/CD pipeline
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: "0.5"
              memory: "512Mi"
            requests:
              cpu: "0.2"
              memory: "256Mi"
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
