name: CICD Pipeline

on:
  push:
    branches: [ "azure" ]
    paths-ignore:
      - 'kubernetes/deployment.yaml'
  pull_request:
    branches: [ "azure" ]

env:
  AZURE_CONTAINER_REGISTRY: "starkbucks"
  CONTAINER_NAME: "starbuck"
  RESOURCE_GROUP: "Exploration"
  CLUSTER_NAME: "test"

jobs:
  security-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test || echo "No tests found, would add tests in a real project"

      - name: Run ESLint
        run: npm run lint

      - name: Build the Docker image
        run: |
          docker build . --file Dockerfile --tag starbucks:latest
          docker images

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: starbucks:latest
          format: 'table'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

  build-docker-image:
    name: Docker Build and Push
    runs-on: ubuntu-latest
    needs: [security-checks]  # This job runs after the security-checks job.
    steps:
        # Checks out the repository this file is in
        - uses: actions/checkout@v4
  
        # Logs in with your Azure credentials
        - name: Azure login
          uses: azure/login@v1.4.6
          with:
            client-id: ${{ env.AZURE_CLIENT_ID }}
            tenant-id: ${{ env.AZURE_TENANT_ID }}
            subscription-id: ${{ env.AZURE_SUBSCRIPTION_ID }}
  
        # Builds and pushes an image up to your Azure Container Registry
        - name: Build and push image to ACR
          run: |
            az acr build --image ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.CONTAINER_NAME }}:${{ github.sha }} --registry ${{ env.AZURE_CONTAINER_REGISTRY }} -g ${{ env.RESOURCE_GROUP }} .
  

  update-k8s-azure:
    name: Update Kubernetes Deployment on Azure
    runs-on: ubuntu-22.04
    needs: [build-docker-image]  # This job runs after the build-docker-image job.
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.TOKEN }}

      - name: Setup Git Config
        run: |
          git config user.name "Github Actions"
          git config user.email "actions@github.com"

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ env.AZURE_CLIENT_ID }}
          tenant-id: ${{ env.AZURE_TENANT_ID }}
          subscription-id: ${{ env.AZURE_SUBSCRIPTION_ID }}

      - name: Login to Azure Container Registry (ACR)
        run: |
          az acr login --name ${{ env.ACR_NAME }}

      - name: Update the Kubernetes Deployment File
        env:
          ACR_REGISTRY: ${{ env.ACR_NAME }}.azurecr.io
          ACR_REPOSITORY: starbucks
          IMAGE_TAG: ${{ github.sha }}
        run: |
          # Define the new image with tag
          NEW_IMAGE="${ACR_REGISTRY}/${ACR_REPOSITORY}:${IMAGE_TAG}"
          echo "New Image: ${NEW_IMAGE}"

          # Update the deployment file directly
          yq eval -i '.spec.template.spec.containers[0].image = env(ACR_REGISTRY) + "/" + env(ACR_REPOSITORY) + ":" + env(IMAGE_TAG)' kubernetes/deployment.yaml
          cat kubernetes/deployment.yaml

          # Verify the change
          echo "Updated deployment to use image: ${NEW_IMAGE}"
          grep -A 1 "image:" kubernetes/deployment.yaml

      - name: Commit and push changes
        run: |
          git add kubernetes/deployment.yaml
          git commit -m "Update Kubernetes deployment with new image tag [skip ci]" || echo "No changes to commit"
          git push
